[package]
name = "pos-server-mongodb"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
mongodb = "2"
serde = { version = "1", features = ["derive"] }
dotenvy = "0.15"
chrono = "0.4.33"
log = "0.4.20"
futures = "0.3.30"
env_logger = "0.11.1"
